package net.storeapp.storeapp.dal.entity;
// Generated May 16, 2020 9:15:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillEntity generated by hbm2java
 */
@Entity
@Table(name="bills"
    ,catalog="storeapp"
)
public class BillEntity  implements java.io.Serializable {


     private Integer id;
     private String type;
     private String details;
     private long totalCost;
     private long pay;
     private long reminder;
     private Date startDate;
     private Date endDate;
     private Date time;
     private Set<CustomerClientEntity> customerClients = new HashSet<CustomerClientEntity>(0);
     private Set<CustomerSupplierEntity> customerSuppliers = new HashSet<CustomerSupplierEntity>(0);

    public BillEntity() {
    }

	
    public BillEntity(String type, String details, long totalCost, long pay, long reminder, Date startDate, Date endDate, Date time) {
        this.type = type;
        this.details = details;
        this.totalCost = totalCost;
        this.pay = pay;
        this.reminder = reminder;
        this.startDate = startDate;
        this.endDate = endDate;
        this.time = time;
    }
    public BillEntity(String type, String details, long totalCost, long pay, long reminder, Date startDate, Date endDate, Date time, Set<CustomerClientEntity> customerClients, Set<CustomerSupplierEntity> customerSuppliers) {
       this.type = type;
       this.details = details;
       this.totalCost = totalCost;
       this.pay = pay;
       this.reminder = reminder;
       this.startDate = startDate;
       this.endDate = endDate;
       this.time = time;
       this.customerClients = customerClients;
       this.customerSuppliers = customerSuppliers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="type", nullable=false, length=100)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="details", nullable=false, length=500)
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }

    
    @Column(name="totalCost", nullable=false, precision=10, scale=0)
    public long getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(long totalCost) {
        this.totalCost = totalCost;
    }

    
    @Column(name="pay", nullable=false, precision=10, scale=0)
    public long getPay() {
        return this.pay;
    }
    
    public void setPay(long pay) {
        this.pay = pay;
    }

    
    @Column(name="reminder", nullable=false, precision=10, scale=0)
    public long getReminder() {
        return this.reminder;
    }
    
    public void setReminder(long reminder) {
        this.reminder = reminder;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", nullable=false, length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="end_date", nullable=false, length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="time", nullable=false, length=8)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bills")
    public Set<CustomerClientEntity> getCustomerClients() {
        return this.customerClients;
    }
    
    public void setCustomerClients(Set<CustomerClientEntity> customerClients) {
        this.customerClients = customerClients;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bills")
    public Set<CustomerSupplierEntity> getCustomerSuppliers() {
        return this.customerSuppliers;
    }
    
    public void setCustomerSuppliers(Set<CustomerSupplierEntity> customerSuppliers) {
        this.customerSuppliers = customerSuppliers;
    }




}


