package net.storeapp.storeapp.dal.entity;
// Generated May 16, 2020 9:15:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BuyEntity generated by hbm2java
 */
@Entity
@Table(name="buy"
    ,catalog="storeapp"
)
public class BuyEntity  implements java.io.Serializable {


     private Integer id;
     private CategoryEntity category;
     private SizeEntity size;
     private String name;
     private long quantity;
     private long price;
     private Date date;
     private Date time;
     private Set<CustomerSupplierEntity> customerSuppliers = new HashSet<CustomerSupplierEntity>(0);

    public BuyEntity() {
    }

	
    public BuyEntity(CategoryEntity category, String name, long quantity, long price, Date date, Date time) {
        this.category = category;
        this.name = name;
        this.quantity = quantity;
        this.price = price;
        this.date = date;
        this.time = time;
    }
    public BuyEntity(CategoryEntity category, SizeEntity size, String name, long quantity, long price, Date date, Date time, Set<CustomerSupplierEntity> customerSuppliers) {
       this.category = category;
       this.size = size;
       this.name = name;
       this.quantity = quantity;
       this.price = price;
       this.date = date;
       this.time = time;
       this.customerSuppliers = customerSuppliers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false)
    public CategoryEntity getCategory() {
        return this.category;
    }
    
    public void setCategory(CategoryEntity category) {
        this.category = category;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="size_id")
    public SizeEntity getSize() {
        return this.size;
    }
    
    public void setSize(SizeEntity size) {
        this.size = size;
    }

    
    @Column(name="name", nullable=false, length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="quantity", nullable=false, precision=10, scale=0)
    public long getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(long quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", nullable=false, precision=10, scale=0)
    public long getPrice() {
        return this.price;
    }
    
    public void setPrice(long price) {
        this.price = price;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="time", nullable=false, length=8)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="buy")
    public Set<CustomerSupplierEntity> getCustomerSuppliers() {
        return this.customerSuppliers;
    }
    
    public void setCustomerSuppliers(Set<CustomerSupplierEntity> customerSuppliers) {
        this.customerSuppliers = customerSuppliers;
    }




}


