package net.storeapp.storeapp.dal.entity;
// Generated May 16, 2020 9:15:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CustomerClientEntity generated by hbm2java
 */
@Entity
@Table(name="customer_client"
    ,catalog="storeapp"
)
public class CustomerClientEntity  implements java.io.Serializable {


     private Integer id;
     private BillEntity bills;
     private CustomerEntity customer;
     private SellEntity sell;

    public CustomerClientEntity() {
    }

	
    public CustomerClientEntity(BillEntity bills) {
        this.bills = bills;
    }
    public CustomerClientEntity(BillEntity bills, CustomerEntity customer, SellEntity sell) {
       this.bills = bills;
       this.customer = customer;
       this.sell = sell;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bills_id", nullable=false)
    public BillEntity getBills() {
        return this.bills;
    }
    
    public void setBills(BillEntity bills) {
        this.bills = bills;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id")
    public CustomerEntity getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(CustomerEntity customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sell_id")
    public SellEntity getSell() {
        return this.sell;
    }
    
    public void setSell(SellEntity sell) {
        this.sell = sell;
    }




}


