package net.storeapp.storeapp.dal.entity;
// Generated May 16, 2020 9:15:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CustomerEntity generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="storeapp"
)
public class CustomerEntity  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<CustomerClientEntity> customerClients = new HashSet<CustomerClientEntity>(0);

    public CustomerEntity() {
    }

	
    public CustomerEntity(String name) {
        this.name = name;
    }
    public CustomerEntity(String name, Set<CustomerClientEntity> customerClients) {
       this.name = name;
       this.customerClients = customerClients;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customer")
    public Set<CustomerClientEntity> getCustomerClients() {
        return this.customerClients;
    }
    
    public void setCustomerClients(Set<CustomerClientEntity> customerClients) {
        this.customerClients = customerClients;
    }




}


