package net.storeapp.storeapp.dal.entity;
// Generated May 16, 2020 9:15:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CustomerSupplierEntity generated by hbm2java
 */
@Entity
@Table(name="customer_supplier"
    ,catalog="storeapp"
)
public class CustomerSupplierEntity  implements java.io.Serializable {


     private Integer id;
     private BillEntity bills;
     private BuyEntity buy;
     private SupplierEntity supplier;

    public CustomerSupplierEntity() {
    }

	
    public CustomerSupplierEntity(BillEntity bills) {
        this.bills = bills;
    }
    public CustomerSupplierEntity(BillEntity bills, BuyEntity buy, SupplierEntity supplier) {
       this.bills = bills;
       this.buy = buy;
       this.supplier = supplier;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bills_id", nullable=false)
    public BillEntity getBills() {
        return this.bills;
    }
    
    public void setBills(BillEntity bills) {
        this.bills = bills;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="buy_id")
    public BuyEntity getBuy() {
        return this.buy;
    }
    
    public void setBuy(BuyEntity buy) {
        this.buy = buy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="supplier_id")
    public SupplierEntity getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(SupplierEntity supplier) {
        this.supplier = supplier;
    }




}


