package net.storeapp.storeapp.dal.entity;
// Generated May 16, 2020 9:15:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SupplierEntity generated by hbm2java
 */
@Entity
@Table(name="supplier"
    ,catalog="storeapp"
)
public class SupplierEntity  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<CustomerSupplierEntity> customerSuppliers = new HashSet<CustomerSupplierEntity>(0);

    public SupplierEntity() {
    }

	
    public SupplierEntity(String name) {
        this.name = name;
    }
    public SupplierEntity(String name, Set<CustomerSupplierEntity> customerSuppliers) {
       this.name = name;
       this.customerSuppliers = customerSuppliers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="supplier")
    public Set<CustomerSupplierEntity> getCustomerSuppliers() {
        return this.customerSuppliers;
    }
    
    public void setCustomerSuppliers(Set<CustomerSupplierEntity> customerSuppliers) {
        this.customerSuppliers = customerSuppliers;
    }




}


